name: untitled14
description: A new Flutter project.
publish_to: none


version: 1.22.5

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any



  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  firebase_auth: ^4.15.0
  go_router: ^12.1.1
  yandex_mapkit: ^3.3.3
  yandex_geocoder: ^2.1.0
  geolocator: ^10.1.0
  json_serializable: ^6.7.1
  file_picker: ^6.1.1
  firebase_storage: ^11.5.3
  cloud_firestore: ^4.13.3
  logger: ^2.0.2+1
  firebase_app_check: ^0.2.1+6
  google_fonts: ^4.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_annotation: ^4.8.1
  build_runner: ^2.4.7





flutter:

  uses-material-design: true
  generate: true




